common/models/Approval.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use common\models\People;

/**
 * This is the model class for table "APPROVAL".
 *
 * @property string $ID
 * @property string $ID_INVENTORY_ITEMS
 * @property string $ID_INVENTORIES
 * @property string $ID_CATEGORIES
 * @property string $ID_INVENTORIES_CHECKIN
 * @property string $ID_ORDER_ITEMS
 * @property string $ID_ORDERS
 * @property string $SKU
 * @property string $ODER
 * @property string $ORDER_NO
 * @property string $ITEMS_CATEGORY_NAME
 * @property string $ITEMS_INVENTORY_NAME
 * @property string $RQ_QUANTITY
 * @property string $APP_QUANTITY
 * @property integer $APPROVED
 * @property string $CURRENT_BALANCE
 * @property string $TOTAL_PRICE
 * @property string $ORDER_DATE
 * @property string $REQUIRED_DATE
 */
class Approval extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    const STATUS_DELETED = 1;
    const STATUS_ACTIVE = 0;

    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new \yii\db\expression('current_timestamp()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
                'value' => Yii::$app->user->id,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'approval';
    }

    public static function primaryKey() {
        return ['id'];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
//            [['id', 'id_inventory_items', 'id_inventories', 'id_categories', 'id_inventories_checkin', 'id_order_items', 'id_orders'
//                , 'rq_quantity', 'app_quantity', 'current_balance', 'total_price', 'unit_price'], 'number'],

            [['id', 'available_per_order', 'id_inventory_items', 'id_inventories', 'id_categories', 'id_inventories_checkin',
                'id_order_items', 'id_orders', 'unit_price', 'rq_quantity', 'app_quantity', 'current_balance', 'total_price'], 'number'],

            [['id_inventory_items'], 'required'],
            [['approved'], 'integer'],
            [['sku'], 'string', 'max' => 50],
            [['order_no'], 'string', 'max' => 20],
            [['items_category_name', 'items_inventory_name'], 'string', 'max' => 255],
            [['order_date', 'required_date'], 'string', 'max' => 7],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'id'),
            'available_per_order' => Yii::t('app', 'Jumlah Yang Ada'),
            'id_inventory_items' => Yii::t('app', 'Id  Barang Inventori'),
            'id_inventories' => Yii::t('app', 'Id  Inventori'),
            'id_categories' => Yii::t('app', 'Id  Kategori'),
            'id_inventories_checkin' => Yii::t('app', 'Id  Inventori Masuk'),
            'id_order_items' => Yii::t('app', 'Id  Barang Pesanan'),
            'id_orders' => Yii::t('app', 'Id  Pesanan'),
            'sku' => Yii::t('app', 'Sku'),
            'unit_price' => Yii::t('app', 'Harga Seunit'),
            'order_no' => Yii::t('app', 'No Pesanan'),
            'items_category_name' => Yii::t('app', 'Nama Kategori Barang'),
            'items_inventory_name' => Yii::t('app', 'Nama Inventori Barang'),
            'rq_quantity' => Yii::t('app', 'Kuantiti Dimohon'),
            'app_quantity' => Yii::t('app', 'Kuantiti Disahkan'),
            'approved' => Yii::t('app', 'Status Pengesahan'),
            'current_balance' => Yii::t('app', 'Kuantiti Semasa Pengeluaran'),
            'total_price' => Yii::t('app', 'Jumlah'),
            'order_date' => Yii::t('app', 'Tarikh Pesanan'),
            'required_date' => Yii::t('app', 'Tarikh Diperlukan'),
        ];
    }

    /**
     * @inheritdoc
     * @return ApprovalQuery the active query used by this AR class.
     */
    public static function find() {
        return new ApprovalQuery(get_called_class());
    }

    public static function fifo($orderId) {
        $data = static::find()->select('id_inventories')->where(['id_orders'=>$orderId])->groupBy('id_inventories')
                ->asArray()
                ->all();
        $itemlist = InventoryItems::find()
                ->joinWith('inventory')
                ->where(['in','inventories.id',$data[0]])
                ->andWhere(['checkout_transaction_id'=>null])
//                ->asArray()
                ->all();
        $up = InventoryItems::checkoutFifo($data[0]);
//        for
        var_dump($up);die();
        return $itemlist;
//        return $data;
    }

    /**
     * @inheritdoc
     */
    public function getInventory() {
        return $this->hasOne(Inventories::className(), ['id' => 'id_inventories']);
    }

    public function getInventoryItem() {
        return $this->hasOne(InventoryItems::className(), ['id' => 'id_inventory_items']);
    }

    public function getOrder() {
        return $this->hasOne(Orders::className(), ['id' => 'id_orders']);
    }

    public function getOrderItem() {
        return $this->hasOne(OrderItems::className(), ['id' => 'id_order_items']);
    }

    public function getCategory() {
        return $this->hasOne(Categories::className(), ['id' => 'id_categories']);
    }

    public function getCreator() {
        return $this->hasOne(People::className(), ['id' => 'created_by']);
    }

    public function getUpdator() {
        return $this->hasOne(People::className(), ['id' => 'updated_by']);
    }

}

frontend/controllers/InventoriesController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Inventories;
use common\models\InventoryItemsSearch;
use common\models\InventoriesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\components\AccessRule;
use kartik\widgets\Alert;
use kartik\widgets\Growl;
use yii\base\Exception;

/**
 * InventoriesController implements the CRUD actions for Inventories model.
 */
class InventoriesController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'delete-multiple' => ['post'],
                    'delete-permanent' => ['post'],
                    'recover' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),],
                'only' => ['create', 'update', 'index', 'view',
                    'delete', 'delete-permanent', 'recover'],
                'rules' => [
                    [
                        'actions' => ['delete-permanent'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['create', 'update', 'delete', 'recover'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Inventories models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new InventoriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPrintBarcode($id,$printChild = 0) {
        Inventories::printInventoryBarcode($id,$printChild);
    }
    public function actionPrintAllSku($id,$printChild = 1) {
        Inventories::printAllSku($id,$printChild);
    }

    public function actionTransactions($id) {
        $inventory = $this->findInventory($id);
        $transactions = \common\models\Transactions::find()
//                ->joinWith('inventory')
//                ->joinWith('inventoriesCheckIn')
//                ->joinWith('inventoriesCheckOut')
//                ->where(['inventories.id'=>$id])
//                ->asArray()
                ->all();
//        var_dump($transactions);die();
        return $this->render('transactions', [
                    'transactions' => $transactions,
                    'inventory' => $inventory,
        ]);
    }

    public function actionItemList($id) {

        $searchModel = new InventoryItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere((['inventories.id' => $id, 'inventory_items.checkout_transaction_id' => NULL
            , 'inventory_items.deleted' => 0, 'inventories.deleted' => 0, 'inventories_checkin.deleted' => 0]));

        return $this->render('item-list', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }

    public function actionItemTransactions($id) {
        $inventory = $this->findInventory($id);
//         var_dump(\common\models\TransactionsAll::find()->where(['inventory_id'=>$id])->all());die();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\TransactionsAll::find()
                   // ->with('checkBy.mpspProfile')
//                    ->with('checkBy.mpspProfile')
                    ->where(['inventory_id' => $id]),
        ]);
        $transactions = $dataProvider->models;

        return $this->render('item-transactions', [
                    'dataProvider' => $dataProvider,
                    'transactions' => $transactions,
                    'inventory' => $inventory,
        ]);
    }

    public function actionPdfItemTransactions($id) {
        $inventory = $this->findInventory($id);die();
//         var_dump(\common\models\TransactionsAll::find()->where(['inventory_id'=>$id])->all());die();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\TransactionsAll::find()->where(['inventory_id' => $id]),
        ]);
        $transactions = $dataProvider->models;
        var_dump($transactions);die();
//        return $this->renderPartial('item-transactions', [
//            'dataProvider' => $dataProvider,
//            'transactions' => $transactions,
//            'inventory' => $inventory,
//        ]);
        $content = $this->renderPartial('_item-transactions', [
            'dataProvider' => $dataProvider,
            'transactions' => $transactions,
            'inventory' => $inventory,
        ]);

        $pdf = new \kartik\mpdf\Pdf([
            'mode' => \kartik\mpdf\Pdf::MODE_CORE, // leaner size using standard fonts
            'content' => $content,
            'options' => [
                'title' => 'Kad Petak ' . $inventory->code_no,
//                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
//            'methods' => [
//                'SetHeader' => ['Generated By: MPSP Estor Application||Generated On: ' . date("r")],
//                'SetFooter' => ['|Page {PAGENO}|'],
//            ]
        ]);
        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/pdf');

        return $pdf->render();
    }

    /**
     * Displays a single Inventories model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
        //return $this->redirect(['index']);
    }

    /**
     * Creates a new Inventories model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Inventories();
        $categories = \common\models\Categories::find()->asArray()->all();
        $categoryArray = \yii\helpers\ArrayHelper::map($categories, 'id', 'name');


        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', [
                    'type' => Growl::TYPE_SUCCESS,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'title' => ' Proses BERJAYA',
                    'message' => ' Data berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            } else {
                \Yii::$app->session->setFlash('error', [
                    'type' => Growl::TYPE_DANGER,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-remove-sign',
                    'title' => ' Proses GAGAL.',
                    'message' => ' Data tidak berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
            //return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                        'model' => $model,
                        'categoryArray' => $categoryArray,
            ]);
        }
    }

    /**
     * Updates an existing Inventories model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $categories = \common\models\Categories::find()->asArray()->all();
        $categoryArray = \yii\helpers\ArrayHelper::map($categories, 'id', 'name');

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', [
                    'type' => Growl::TYPE_SUCCESS,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'title' => ' Proses BERJAYA',
                    'message' => ' Data berjaya dikemaskini.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            } else {
                \Yii::$app->session->setFlash('error', [
                    'type' => Growl::TYPE_DANGER,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-remove-sign',
                    'title' => ' Proses GAGAL.',
                    'message' => ' Data tidak berjaya dikemaskini.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
            //return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                        'model' => $model,
                        'categoryArray' => $categoryArray,
            ]);
        }
    }

    /**
     * Deletes an existing Inventories model.

frontend/views/inventories/item-transactions.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\EstorInventories */

//$this->title = $inventory->id;
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Estor Inventories'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
//var_dump($order);
//var_dump($listItem[0]);die();
//die();
?>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Kad Petak</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <!--                    <div class="btn-group">
                                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-wrench"></i></button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Action</a></li>
                                                <li><a href="#">Another action</a></li>
                                                <li><a href="#">Something else here</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Separated link</a></li>
                                            </ul>
                                        </div>-->
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!--/.box-header-->
            <div class="box-body table-responsive">
                <div>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td colspan="2" style="width:25%">Rujuk Kawalan Stok :</th>
                                <td colspan="5" style="width:40%"><?= $inventory->card_no ?></th>
                                <td colspan="2" style="width:18%">Nombor Kod:</th>
                                <td colspan="4" style="width:auto"><?= $inventory->code_no ?></th>
                            </tr>
                            <tr>
                                <td colspan="2">Perihal Stok:</th>
                                <td colspan="11"><?= $inventory->description ?></th>
                            </tr>
                            <tr>
                                <td colspan="2">Kumpulan Stok:</th>
                                <td colspan="5" style="width:13%"><?= $inventory->category->name ?></th>
                                <td colspan="2" style="width:15%">Lokasi Stok:</th>
                                <td colspan="4"><?= $inventory->location ?></th>
                            </tr>
                        </tbody>
                    </table>
                    <!--/.row-->
                </div>
            </div>
            <div class="box-body table-responsive">
                <div>
                    <table class="kv-grid-table table table-hover table-bordered table-striped table-condensed kv-table-wrap">
                    <!--<table class="table table-bordered table-hover">-->
                        <thead>
                            <!--<tr class="kartik-sheet-style">-->
                            <tr>
                                <th class="text-center" rowspan="2">Bil</th>
                                <th class="text-center" rowspan="2">Tarikh</th>
                                <th class="text-center" rowspan="2">Keterangan</th>
                                <th class="text-center" rowspan="2">No Rujukan</th>
                                <th class="text-center" colspan="4" style="text-align: center">Kuantiti</span></th>
                                <th class="text-center" rowspan="2">Nama Pegawai Stor</th>
                            </tr>
                            <tr>
                                <th class="text-center">Terima</th>
                                <th class="text-center">Seunit (RM)</th>
                                <th class="text-center">Keluar</th>
                                <th class="text-center">Baki</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="text-center">/</td>
                                <td class="text-center"></td>
                                <td class="text-center"></td>
                                <td colspan="4" class="text-right">Baki dibawa kehadapan</td>
                                <!--<td class="text-right">baki kad lepas</td>-->
                                <?php if ($transactions) { ?>
                                    <td class="text-center"><?= $transactions[0]->count_current - $transactions[0]->count_in + $transactions[0]->count_out ?></td>
                                <?php } else { ?>
                                    <td class="center">0</td>
                                <?php } ?>
                            </tr>
                            <?php
                            if (sizeof($transactions) >= 1) {
                                foreach ($transactions as $i => $transaction) {
                                    ?>
                                    <tr>
                                        <td class="text-center"><?= $i + 1 ?></td>
                                        <td class="text-center"><?= $transaction->check_date; ?></td>
                                        <td class="text-center"><?php
                                            if ($transaction->type == 1) {
                                                echo 'in';
                                            } else {
//                                            echo 'reg_no';
//                                            echo $transaction->id;
                                                echo $transaction->order->vehicle_id;
//                                            echo $transaction->vehicle->reg_no;
                                            }
                                            ?></td>
                                        <td class="text-center"><?= $transaction->refference; ?></td>
                                        <td class="text-center"><?= $transaction->count_in; ?></td>
                                        <td class="text-center"><?= $transaction->unit_price; ?></td>
                                        <td class="text-center"><?= $transaction->count_out; ?></td>
                                        <td class="text-center"><?= $transaction->count_current; ?></td>
                                        <td class="text-center"><?= $transaction->checkBy->mpspProfile->nama ?><?php
                                            if ($transaction->type == 2 && isset($transaction->order->vehicle)) {
                                                echo '<br>Kenderaan :' . $transaction->order->vehicle->reg_no;
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } else { ?>
                                <?php for ($j = 0; $j < 10; $j++) { ?>
                                    <tr>
                                        <td class="kv-align-center"><?= $j + 1 ?></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-center">&nbsp;</td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>
                        </tbody>
                    </table>
                    <!--/.row-->
                </div>
            </div>
            <!--./box-body-->
            <div class="box-footer">
                <div class="pull-right">
                    <?= yii\widgets\LinkPager::widget(['pagination' => $dataProvider->pagination,]); ?>
                    <?= Html::a('<i class="glyphicon glyphicon-list-alt"></i> Format KEW-PS 4', ['official-form/pdf-kewps4', 'id' => $inventory->id,'printAll' => true], ['class' => 'btn btn-info', 'target' => '_blank']); ?>
                    <?= Html::a('<i class="glyphicon glyphicon-print"></i> Print', ['inventories/pdf-item-transactions', 'id' => $inventory->id], ['class' => 'btn btn-info', 'target' => '_blank']); ?>
                </div>

                <!--footer-->
                <!--/.row-->
            </div>
            <!--/.box-footer-->
        </div>
        <!--/.box-->
    </div>
    <!--/.col-->
</div>

frontend/views/inventories/transactions.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\EstorInventories */

//$this->title = $inventory->id;
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Estor Inventories'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;

//var_dump($inventory);
//var_dump($listItem[0]);die();
//die();
?>


<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Kad Petak</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <!--                    <div class="btn-group">
                                            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-wrench"></i></button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Action</a></li>
                                                <li><a href="#">Another action</a></li>
                                                <li><a href="#">Something else here</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Separated link</a></li>
                                            </ul>
                                        </div>-->
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <!--/.box-header-->
            <div class="box-body table-responsive">
                <div>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td colspan="2" style="width:25%">Rujuk Kawalan Stok :</th>
                                <td colspan="4" style="width:40%"><?= $inventory->card_no ?></th>
                                <td colspan="2" style="width:18%">Nombor Kod:</th>
                                <td colspan="4" style="width:auto"><?= $inventory->code_no ?></th>
                            </tr>
                            <tr>
                                <td colspan="2">Perihal Stok:</th>
                                <td colspan="10"><?= $inventory->description ?></th>
                            </tr>
                            <tr>
                                <td colspan="2">Kumpulan Stok:</th>
                                <td colspan="1" style="width:13%"><?= $inventory->category->name ?></th>
                                <td colspan="2" style="width:15%">Lokasi Stok:</th>
                                <td colspan="8"><?= $inventory->location ?></th>
                            </tr>
                        </tbody>
                    </table>
                    <!--/.row-->
                </div>
            </div>
            <div class="box-body table-responsive">
                <div>
                    <table class="kv-grid-table table table-hover table-bordered table-striped table-condensed kv-table-wrap">
                    <!--<table class="table table-bordered table-hover">-->
                        <thead>
                            <!--<tr class="kartik-sheet-style">-->
                            <tr>
                                <th rowspan="2">Bil</th>
                                <th rowspan="2">Tarikh</th>
                                <th rowspan="2">Keterangan</th>
                                <th rowspan="2">No Rujukan</th>
                                <th colspan="4" style="text-align: center">Kuantiti</span></th>
                                <th rowspan="2">Nama Pegawai Stor</th>
                            </tr>
                            <tr>
                                <th>Terima</th>
                                <th>Seunit (RM)</th>
                                <th>Keluar</th>
                                <th>Baki</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>/</td>
                                <td></td>
                                <td></td>
                                <td colspan="3" style="text-align: right">Baki</td>
                                <td style="text-align: right">baki kad lepas</td>
                                <td></td>
                            </tr>
                            <?php
                            foreach ($transactions as $i=>$transaction) {
                                ?>
                                <tr>
                                    <td class="kv-align-center"><?= $i+1 ?></td>
                                    <td><?= $transaction['check_date']; ?></td>
                                    <td><?= $transaction['type']; ?></td>
                                    <td><?= $transaction['id']; ?></td>
                                    <td><?= $transaction['inventoriesCheckIn']['id']; ?></td>
                                    <td><?= $transaction['inventory']['quantity']; ?></td>
                                    <td><?= $transaction['orderItems']['app_quantity']; ?></td>
                                    <td><?= $transaction['id']; ?></td>
                                    <td><?= $transaction['id']; ?></td>
                                    <td><?= $transaction['id']; ?></td>
                                    <td><?= $transaction['id']; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <!--/.row-->
                </div>
            </div>
            <!--./box-body-->
            <div class="box-footer">
                <!--footer-->
                <!--/.row-->
            </div>
            <!--/.box-footer-->
        </div>
        <!--/.box-->
    </div>
    <!--/.col-->
</div>